services:

  db:
    image: postgres
    container_name: postgresql_txuribeltz
    #restart: always
    shm_size: 128mb
    ports:
      - 5433:5432
    
    volumes:
    - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql #datubasea inizializatzeko eta datuak sartzeko
    - ./postgresql:/var/lib/postgresql

    environment:
        POSTGRES_USER: admin #datubasearen erabiltzailea
        POSTGRES_PASSWORD: admin #datubasearen pasahitza
        POSTGRES_DB: txuribeltz #datubasearen izena

  adminer:
    image: adminer
    #restart: always
    ports:
      - 8081:8080